package view.menus;

import model.ClassroomDataModel;
import model.FacultyDataModel;
import model.OfferedCourseDataModel;
import model.StudentDataModel;
import view.inputforms.InputClassroomForm;
import view.inputforms.InputFacultyForm;
import view.inputforms.InputOfferedCourseForm;
import view.inputforms.InputStudentForm;
import view.reportforms.ClassroomReportForm;
import view.reportforms.FacultyReportForm;
import view.reportforms.OfferedCourseReportForm;
import view.reportforms.StudentReportForm;

public class TopLevelMenu extends javax.swing.JFrame {
    
    // This is the data model that will get passed to all classroom forms. 
    ClassroomDataModel classroomdatamodel = new ClassroomDataModel();
    
    // This is the data model that will get passed to all faculty forms. 
    FacultyDataModel facultydatamodel = new FacultyDataModel();
    
    // This is the data model that will get passed to all offered course forms. 
    OfferedCourseDataModel offeredcoursedatamodel = new OfferedCourseDataModel();
    
    // This is the data model that will get passed to all student forms. 
    StudentDataModel studentdatamodel = new StudentDataModel();

    public TopLevelMenu() {
        // Initialize the components
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuOption = new javax.swing.JMenuItem();
        classroommenu = new javax.swing.JMenu();
        classroomAddMenu = new javax.swing.JMenuItem();
        classroomListMenu = new javax.swing.JMenuItem();
        classmenu = new javax.swing.JMenu();
        addClass = new javax.swing.JMenuItem();
        listClasses = new javax.swing.JMenuItem();
        studentmenu = new javax.swing.JMenu();
        addStudentMenuItem = new javax.swing.JMenuItem();
        listStudentsMenuItem = new javax.swing.JMenuItem();
        faculty = new javax.swing.JMenu();
        addfaculty = new javax.swing.JMenuItem();
        listfaculty = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        exitMenuOption.setText("Exit");
        exitMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuOptionActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuOption);

        jMenuBar1.add(jMenu1);

        classroommenu.setText("Classroom");

        classroomAddMenu.setText("Add Classroom");
        classroomAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classroomAddMenuActionPerformed(evt);
            }
        });
        classroommenu.add(classroomAddMenu);

        classroomListMenu.setText("List Classrooms");
        classroomListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classroomListMenuActionPerformed(evt);
            }
        });
        classroommenu.add(classroomListMenu);

        jMenuBar1.add(classroommenu);

        classmenu.setText("Courses");

        addClass.setText("Add Course");
        addClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassActionPerformed(evt);
            }
        });
        classmenu.add(addClass);

        listClasses.setText("List Courses");
        listClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClassesActionPerformed(evt);
            }
        });
        classmenu.add(listClasses);

        jMenuBar1.add(classmenu);

        studentmenu.setText("Students");

        addStudentMenuItem.setText("Add Student");
        addStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentMenuItemActionPerformed(evt);
            }
        });
        studentmenu.add(addStudentMenuItem);

        listStudentsMenuItem.setText("List Students");
        listStudentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentsMenuItemActionPerformed(evt);
            }
        });
        studentmenu.add(listStudentsMenuItem);

        jMenuBar1.add(studentmenu);

        faculty.setText("Faculty");

        addfaculty.setText("Add Faculty");
        addfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfacultyActionPerformed(evt);
            }
        });
        faculty.add(addfaculty);

        listfaculty.setText("List Faculty");
        listfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listfacultyActionPerformed(evt);
            }
        });
        faculty.add(listfaculty);

        jMenuBar1.add(faculty);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classroomListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classroomListMenuActionPerformed
        ClassroomReportForm listClassroomForm = new ClassroomReportForm(classroomdatamodel);        
        listClassroomForm.setSize(800,600);
        listClassroomForm.setVisible(true);  
    }//GEN-LAST:event_classroomListMenuActionPerformed

    private void classroomAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classroomAddMenuActionPerformed
        InputClassroomForm addClassroomForm = new InputClassroomForm(classroomdatamodel);
        addClassroomForm.setSize(500,250);
        addClassroomForm.setVisible(true);
    }//GEN-LAST:event_classroomAddMenuActionPerformed

    private void addfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfacultyActionPerformed
        InputFacultyForm addfaculty = new InputFacultyForm(facultydatamodel);
        addfaculty.setSize(600,500);
        addfaculty.setVisible(true);
    }//GEN-LAST:event_addfacultyActionPerformed

    private void listfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listfacultyActionPerformed
        FacultyReportForm listfaculty = new FacultyReportForm(facultydatamodel);        
        listfaculty.setSize(800,600);
        listfaculty.setVisible(true);
    }//GEN-LAST:event_listfacultyActionPerformed

    private void addClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassActionPerformed
        InputOfferedCourseForm addofferedcourse = new InputOfferedCourseForm(offeredcoursedatamodel);
        addofferedcourse.setSize(550,180);
        addofferedcourse.setVisible(true);
    }//GEN-LAST:event_addClassActionPerformed

    private void listClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClassesActionPerformed
        OfferedCourseReportForm listofferedcourse = new OfferedCourseReportForm(offeredcoursedatamodel);        
        listofferedcourse.setSize(800,600);
        listofferedcourse.setVisible(true);
    }//GEN-LAST:event_listClassesActionPerformed

    private void exitMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuOptionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuOptionActionPerformed

    private void addStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentMenuItemActionPerformed
        InputStudentForm addstudentcourse = new InputStudentForm(studentdatamodel);
        addstudentcourse.setSize(550,400);
        addstudentcourse.setVisible(true);
    }//GEN-LAST:event_addStudentMenuItemActionPerformed

    private void listStudentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentsMenuItemActionPerformed
        StudentReportForm liststudent = new StudentReportForm(studentdatamodel);        
        liststudent.setSize(800,600);
        liststudent.setVisible(true);
    }//GEN-LAST:event_listStudentsMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addClass;
    private javax.swing.JMenuItem addStudentMenuItem;
    private javax.swing.JMenuItem addfaculty;
    private javax.swing.JMenu classmenu;
    private javax.swing.JMenuItem classroomAddMenu;
    private javax.swing.JMenuItem classroomListMenu;
    private javax.swing.JMenu classroommenu;
    private javax.swing.JMenuItem exitMenuOption;
    private javax.swing.JMenu faculty;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listClasses;
    private javax.swing.JMenuItem listStudentsMenuItem;
    private javax.swing.JMenuItem listfaculty;
    private javax.swing.JMenu studentmenu;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        TopLevelMenu topmenu = new TopLevelMenu();
        topmenu.setVisible(true);
    }

}
