package view.inputforms;

import baseclasses.Student;
import baseclasses.StudentCourse;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.StudentDataModel;

public class InputStudentForm extends javax.swing.JFrame {

    ArrayList<Student> listOfStudents;
    /**
     * default constructor
     */
    public InputStudentForm(StudentDataModel studentData) {

        // Initialize all the components on the form
        initComponents();

        // Retrieve the list of students from the data model and store locally
        this.listOfStudents = studentData.getListOfStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        ssnTextfield = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        gpaField = new javax.swing.JTextField();
        addCourseButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateOfBirthField = new javax.swing.JTextField();
        dateOfGraduationField = new javax.swing.JTextField();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nameField);
        nameField.setBounds(160, 50, 200, 30);
        getContentPane().add(addressField);
        addressField.setBounds(160, 90, 200, 30);
        getContentPane().add(ssnTextfield);
        ssnTextfield.setBounds(160, 130, 200, 30);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(390, 130, 110, 29);

        jLabel1.setText("Add Student");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 130, 16);

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 140, 16);

        jLabel3.setText("Address:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 140, 16);

        jLabel4.setText("SSN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 140, 16);

        jLabel5.setText("Data Of Birth");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 130, 16);

        jLabel6.setText("Data Of Graduation");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 240, 120, 16);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(390, 50, 110, 29);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(390, 90, 110, 29);

        jLabel11.setText("GPA");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 290, 120, 16);
        getContentPane().add(gpaField);
        gpaField.setBounds(160, 290, 80, 20);

        addCourseButton.setText("Add Courses");
        addCourseButton.setEnabled(false);
        getContentPane().add(addCourseButton);
        addCourseButton.setBounds(390, 160, 110, 29);

        jLabel8.setText("MM-DD-YYYY");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 240, 160, 16);

        jLabel9.setText("MM-DD-YYYY");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 200, 160, 16);
        getContentPane().add(dateOfBirthField);
        dateOfBirthField.setBounds(160, 200, 130, 26);
        getContentPane().add(dateOfGraduationField);
        dateOfGraduationField.setBounds(160, 240, 130, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Create a new offered course object
        Student aStudent = new Student();

        // Retrieve the values from the input form
        String name = this.nameField.getText();
        String address = this.addressField.getText();
        String ssn = this.ssnTextfield.getText();
        String dob = this.dateOfBirthField.getText();
        String dog = this.dateOfGraduationField.getText();
        String gpa = this.gpaField.getText();
       // Set the values to report form
        aStudent.setName(name);
        aStudent.setAddress(address);
        aStudent.setSocialSecurityNumber(ssn);
        aStudent.setCurrentGPA(Float.parseFloat(gpa));

        // Add to the list in the data model
        this.listOfStudents.add(aStudent);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.nameField.setText("");
        this.addressField.setText("");
        this.ssnTextfield.setText("");
        this.dateOfBirthField.setText("");
        this.dateOfGraduationField.setText("");
        this.gpaField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField dateOfBirthField;
    private javax.swing.JTextField dateOfGraduationField;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField gpaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField ssnTextfield;
    // End of variables declaration//GEN-END:variables
}
