package view.inputforms;

import baseclasses.OfferedCourse;
import java.util.ArrayList;
import model.OfferedCourseDataModel;

public class InputOfferedCourseForm extends javax.swing.JFrame {

    ArrayList<OfferedCourse> listOfOfferedCourse;
    
    public InputOfferedCourseForm(OfferedCourseDataModel offeredCourseData) {

        // Initialize all the components on the form
        initComponents();

        // Retrieve the list of offered courses from the data model and store locally
        this.listOfOfferedCourse = offeredCourseData.getListOfOfferedCourse();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        courseIdField = new javax.swing.JTextField();
        courseName = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(courseIdField);
        courseIdField.setBounds(160, 50, 200, 30);
        getContentPane().add(courseName);
        courseName.setBounds(160, 90, 200, 30);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(400, 110, 80, 29);

        jLabel1.setText("Add A Course");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 150, 16);

        jLabel2.setText("Course Number:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 130, 16);

        jLabel3.setText("Course Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 140, 16);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(400, 50, 80, 29);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(400, 80, 80, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Create a new offered course object
        OfferedCourse aOfferedCourse = new OfferedCourse();

        // Retrieve the values from the input form
        String courseId = this.courseIdField.getText();
        String courseName = this.courseName.getText();
        
       // Set the values to report form
        aOfferedCourse.setCourseId(courseId);
        aOfferedCourse.setCourseName(courseName);

        // Add to the list in the data model
        this.listOfOfferedCourse.add(aOfferedCourse);                                          
    }//GEN-LAST:event_saveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.courseIdField.setText("");
        this.courseName.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField courseIdField;
    private javax.swing.JTextField courseName;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
